# Generated by Django 3.2.5 on 2021-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210810_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editions',
        ),
        migrations.AddField(
            model_name='author',
            name='editions',
            field=models.ManyToManyField(to='articles.Edition'),
        ),
    ]
